config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  get 'about', to: 'pages#about'

  resources :product_orders, except: [:edit, :show, :update]
  resources :products

  get 'signup', to: 'users#new'
  get 'vendors', to: 'users#vendors'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :categories, except: [:delete]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :product_categories
  has_many :products, through: :product_categories
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates_uniqueness_of :name
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_user, except: [:index, :show]
  before_action :require_admin, except: [:index, :show]
  def index
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end

  def new
    @category = Category.new
  end

  def show
    @category = Category.find(params[:id])
    @category_products = @category.products.paginate(page: params[:page], per_page: 5)
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "Category was created successfully"
      redirect_to categories_path
    else
      render 'new'
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:success] = "Category name was successfully updated"
      redirect_to category_path(@category)
    else
      render 'edit'
    end
  end

  private
  def category_params
    params.require(:category).permit(:name)
  end

  def require_user
    if !logged_in?
      flash[:danger] = "Only users can perform that action"
      redirect_to categories_path
    end
  end

  def require_admin
    if !current_user.admin?
      flash[:danger] = "Only admin can perform that action"
      redirect_to categories_path
    end
  end
end

app/views/categories/_category.html.erb
<span class="badge"><%= link_to category.name, category_path(category) %> &nbsp;</span>

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category %>

<%= form_for(@category, :html => {class: "form-horizontal", role: "form"}) do |f| %>
  <div class="form-group">
    <div class="control-label col-sm-2">
          <%= f.label :name %>
    </div>
    <div class="col-sm-8">
      <%= f.text_field :name, class: "form-control", placeholder: "Enter category name", autofocus: true %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary btn-lg" %>
    </div>
  </div>
<% end %>

  <div class="col-xs-4 col-xs-offset-4">
    [ <%= link_to "Cancel request and return to products listing", products_path %> ]
  </div>

app/views/categories/edit.html.erb
<h1 align="center">Edit category name</h1>

<%= render 'form' %>

app/views/categories/index.html.erb
<h1 align="center">Categories</h1>

<div align="center">
  <%= will_paginate %>
  <% @categories.each do |category| %>
    <ul class="listing">
      <div class="row">
        <div class="well col-md-4 col-md-offset-4">
          <li class="product-title">
            <%= link_to "#{category.name}", category_path(category) %>
          </li>
          <li>
            <small><%= pluralize(category.products.count, "product") %></small>
          </li>
        </div>
      </div>
    </ul>
  <% end %>
  <%= will_paginate %>
</div>

app/views/categories/new.html.erb
<h1 align="center">New Category</h1>

<%= render 'categories/form' %>

app/views/categories/show.html.erb
<h1 align="center"><%= @category.name %></h1>

<div align="center">
  <% if logged_in? and current_user.admin? %>
  <div class="row">
    <span class="badge"><%= link_to "Edit category name", edit_category_path(@category) %></span>
  </div>
  <% end %>
  <%= will_paginate @category_products %>
</div>

<div align="center">
  <% @category_products.each do |product| %>
    <div class="row">
      <div class="col-xs-8 col-xs-offset-2">
        <div class="well well-lg">
          <div class="product-title">
            <%= link_to product.title, product_path(product) %>
          </div>
          <div class="product-body">
            <h5>Retail Price: <%= "$#{product.price}" %></h5>
          </div>

          <% if product.image.size > 0 %>
          <div class="product-image">
            <%= image_tag product.image.med.url %>
          </div>
          <% end %>

          <div class="product-body">
            <%= truncate(product.description, length: 100) %>
            <div class="product-meta-details">
              <small>Distributed by: <%= product.user.username if product.user %>
            </small>
            </div>
          </div>
          <% if product.categories.any? %>
          <p>Categories: <%= render product.categories %></p>
          <% end %>
          <% if logged_in? && (current_user == product.user || current_user.admin?) %>
          <%= link_to 'Edit product', edit_product_path(product), class: "btn btn-xs btn-primary" %>
          <%= link_to 'Delete this product', product_path(product), method: :delete, data: { confirm: "Are you sure you want to delete this product?" }, class: "btn btn-xs btn-danger" %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div align="center">
  <%= will_paginate @category_products%>
</div>